# Generated by Django 4.2.5 on 2023-10-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('balance', models.FloatField()),
                ('spouse', models.CharField(blank=True, max_length=50, null=True)),
                ('joint_balance', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
