# Generated by Django 4.2.5 on 2023-10-05 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IncomeTracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualaccount',
            old_name='spouse',
            new_name='partner',
        ),
        migrations.AddField(
            model_name='individualaccount',
            name='partner_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualaccount',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
