# Generated by Django 4.2.5 on 2023-10-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IncomeTracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualaccount',
            old_name='balance',
            new_name='income',
        ),
        migrations.RenameField(
            model_name='individualaccount',
            old_name='spouse',
            new_name='partner',
        ),
        migrations.AddField(
            model_name='individualaccount',
            name='partner_income',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
