# Generated by Django 4.2.5 on 2023-10-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IncomeTracker', '0002_rename_balance_individualaccount_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualaccount',
            name='joint_balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='individualaccount',
            name='partner',
            field=models.CharField(max_length=50),
        ),
    ]
