# Generated by Django 4.2.5 on 2023-10-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IncomeTracker', '0002_rename_spouse_individualaccount_partner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualaccount',
            old_name='balance',
            new_name='user_income',
        ),
        migrations.AlterField(
            model_name='individualaccount',
            name='joint_balance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individualaccount',
            name='partner',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individualaccount',
            name='partner_income',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
