# Generated by Django 4.2.5 on 2023-10-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IncomeTracker', '0003_rename_balance_individualaccount_user_income_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualaccount',
            old_name='partner_income',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='individualaccount',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='individualaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='individualaccount',
            name='user_income',
        ),
        migrations.AddField(
            model_name='individualaccount',
            name='spouse',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='individualaccount',
            name='joint_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
