# Generated by Django 4.2.5 on 2023-09-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialAdvisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField()),
            ],
        ),
    ]
