# Generated by Django 4.2.5 on 2023-09-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialAdvisor', '0002_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointaccount',
            name='proportionate_balance1',
            field=models.FloatField(default=101),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jointaccount',
            name='proportionate_balance2',
            field=models.FloatField(default=202),
            preserve_default=False,
        ),
    ]
