# Generated by Django 4.2.5 on 2023-09-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialAdvisor', '0003_jointaccount_proportionate_balance1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advice',
        ),
        migrations.RemoveField(
            model_name='jointexpense',
            name='account',
        ),
        migrations.RemoveField(
            model_name='jointsaving',
            name='account',
        ),
        migrations.RemoveField(
            model_name='saving',
            name='account',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='IndividualAccount',
        ),
        migrations.DeleteModel(
            name='JointAccount',
        ),
        migrations.DeleteModel(
            name='JointExpense',
        ),
        migrations.DeleteModel(
            name='JointSaving',
        ),
        migrations.DeleteModel(
            name='Saving',
        ),
    ]
